/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.21
 * Generated at: 2026-05-13 07:11:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.ecommerce.ecommerce.model.Product;
import com.ecommerce.ecommerce.model.Review;
import java.util.List;

public final class display_002dproducts_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.ecommerce.ecommerce.model.Product");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.ecommerce.ecommerce.model.Review");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>E-Store Dashboard</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        body { font-family: 'Segoe UI', sans-serif; margin: 0; background: #f0f2f5; color: #333; }\r\n");
      out.write("        .top-bar { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 15px 30px; display: flex; justify-content: space-between; align-items: center; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }\r\n");
      out.write("        .container { max-width: 1100px; margin: 30px auto; padding: 0 20px; }\r\n");
      out.write("        .card { background: white; padding: 25px; border-radius: 15px; box-shadow: 0 5px 20px rgba(0,0,0,0.05); margin-bottom: 30px; }\r\n");
      out.write("        h3 { color: #764ba2; border-left: 5px solid #667eea; padding-left: 15px; margin-bottom: 20px; }\r\n");
      out.write("\r\n");
      out.write("        .error-alert {\r\n");
      out.write("            color: #ff4757; background: #ffe0e3; padding: 15px; border-radius: 12px; margin-bottom: 20px;\r\n");
      out.write("            border-left: 6px solid #ff4757; display: flex; align-items: center; gap: 10px; animation: shake 0.5s ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("        @keyframes shake { 0%, 100% { transform: translateX(0); } 25% { transform: translateX(-5px); } 75% { transform: translateX(5px); } }\r\n");
      out.write("\r\n");
      out.write("        .admin-form-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 15px; }\r\n");
      out.write("        .input-style { width: 100%; padding: 12px; border: 1px solid #ddd; border-radius: 8px; outline: none; transition: 0.3s; }\r\n");
      out.write("        .input-style:focus { border-color: #764ba2; box-shadow: 0 0 5px rgba(118,75,162,0.2); }\r\n");
      out.write("        .full-width { grid-column: span 2; }\r\n");
      out.write("        .btn-add { background: #764ba2; color: white; border: none; padding: 12px; border-radius: 8px; cursor: pointer; font-weight: bold; grid-column: span 2; transition: 0.3s; }\r\n");
      out.write("        .btn-add:hover { background: #667eea; transform: translateY(-2px); }\r\n");
      out.write("\r\n");
      out.write("        table { width: 100%; border-collapse: collapse; border-radius: 10px; overflow: hidden; }\r\n");
      out.write("        th { background: #f8f9fa; padding: 15px; text-align: left; color: #764ba2; }\r\n");
      out.write("        td { padding: 15px; border-bottom: 1px solid #f0f0f0; }\r\n");
      out.write("        .product-link { color: #667eea; text-decoration: none; font-weight: bold; }\r\n");
      out.write("        .btn-delete { color: #ff4757; text-decoration: none; font-weight: 600; }\r\n");
      out.write("        .logout-btn { background: rgba(255,255,255,0.2); color: white; padding: 8px 15px; text-decoration: none; border-radius: 8px; font-weight: 600; }\r\n");
      out.write("\r\n");
      out.write("        .review-card { background: #f9f9ff; padding: 15px; border-radius: 10px; margin-bottom: 15px; border: 1px solid #eee; border-left: 4px solid #764ba2; }\r\n");
      out.write("        .stars { color: #ffa502; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"top-bar\">\r\n");
      out.write("    <div><i class=\"fas fa-user-circle\"></i> Welcome, <b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b> (");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${role}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</div>\r\n");
      out.write("    <div>\r\n");
      out.write("        <a href=\"deleteAccount\" onclick=\"return confirm('🚨 Are you sure you want to delete your account permanently?')\" style=\"color: #ffcccc; text-decoration: none; margin-right: 20px; font-size: 0.9em;\">Delete Account</a>\r\n");
      out.write("        <a href=\"logout\" class=\"logout-btn\"><i class=\"fas fa-sign-out-alt\"></i> Sign Out</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    ");
 String role = (String) request.getAttribute("role"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
 if(request.getAttribute("errorMessage") != null) { 
      out.write("\r\n");
      out.write("    <div class=\"error-alert\">\r\n");
      out.write("        <i class=\"fas fa-exclamation-triangle\"></i>\r\n");
      out.write("        <span><b>Oops!</b> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMessage}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
 if("ADMIN".equals(role)) { 
      out.write("\r\n");
      out.write("    <div class=\"card\" style=\"border: 1px dashed #764ba2; background: #fffbff;\">\r\n");
      out.write("        <h3><i class=\"fas fa-plus-circle\"></i> Add New Product</h3>\r\n");
      out.write("        <form action=\"manageProduct?action=add\" method=\"post\" class=\"admin-form-grid\">\r\n");
      out.write("            <input type=\"text\" name=\"name\" class=\"input-style\" placeholder=\"Item Name\" required>\r\n");
      out.write("            <input type=\"number\" step=\"0.01\" name=\"price\" class=\"input-style\" placeholder=\"Price ($)\" required>\r\n");
      out.write("            <input type=\"text\" name=\"description\" class=\"input-style full-width\" placeholder=\"Detailed Description\">\r\n");
      out.write("            <input type=\"text\" name=\"imageUrl\" class=\"input-style full-width\" placeholder=\"Image URL\">\r\n");
      out.write("            <button type=\"submit\" class=\"btn-add\">Save to Inventory</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <h3><i class=\"fas fa-boxes\"></i> Available Products</h3>\r\n");
      out.write("        <table>\r\n");
      out.write("            <thead>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>ID</th>\r\n");
      out.write("                <th>Product Name</th>\r\n");
      out.write("                <th>Price</th>\r\n");
      out.write("                <th>Actions</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("            ");

                List<Product> products = (List<Product>) request.getAttribute("data");
                if (products != null && !products.isEmpty()) {
                    for(Product p : products) {
            
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>#");
      out.print( p.getId() );
      out.write("</td>\r\n");
      out.write("                <td><a href=\"productDetail?id=");
      out.print( p.getId() );
      out.write("\" class=\"product-link\">");
      out.print( p.getName() );
      out.write("</a></td>\r\n");
      out.write("                <td><b style=\"color: #2ed573;\">$");
      out.print( String.format("%.2f", p.getPrice()) );
      out.write("</b></td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    ");
 if("ADMIN".equals(role)) { 
      out.write("\r\n");
      out.write("                    <a href=\"manageProduct?action=delete&id=");
      out.print( p.getId() );
      out.write("\" class=\"btn-delete\" onclick=\"return confirm('Are you sure you want to remove this product?')\"><i class=\"fas fa-trash\"></i></a>\r\n");
      out.write("                    ");
 } else { 
      out.write("\r\n");
      out.write("                    <span style=\"color: #ccc;\"><i class=\"fas fa-lock\"></i> View Only</span>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");

                }
            } else {
            
      out.write("\r\n");
      out.write("            <tr><td colspan=\"4\" style=\"text-align: center; color: #999;\">No products found in inventory.</td></tr>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <h3><i class=\"fas fa-comments\"></i> Customer Reviews</h3>\r\n");
      out.write("        <div class=\"reviews-list\">\r\n");
      out.write("            ");

                List<Review> allReviews = (List<Review>) request.getAttribute("reviews");
                if (allReviews != null && !allReviews.isEmpty()) {
                    for(Review r : allReviews) {
            
      out.write("\r\n");
      out.write("            <div class=\"review-card\">\r\n");
      out.write("                <div style=\"display: flex; justify-content: space-between; align-items: center;\">\r\n");
      out.write("                    <b><i class=\"fas fa-user\"></i> ");
      out.print( r.getUsername() );
      out.write("</b>\r\n");
      out.write("                    <span class=\"stars\">\r\n");
      out.write("                        ");
 for(int i=0; i<r.getRating(); i++) { 
      out.write(' ');
      out.write('★');
      out.write(' ');
 } 
      out.write("\r\n");
      out.write("                    </span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p style=\"margin: 10px 0 5px; color: #555;\">");
      out.print( r.getComment() );
      out.write("</p>\r\n");
      out.write("                <small style=\"color: #999; font-size: 0.8em;\">For Product ID: #");
      out.print( r.getProductId() );
      out.write("</small>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");

                }
            } else {
            
      out.write("\r\n");
      out.write("            <p style=\"text-align: center; color: #999; padding: 20px;\">No reviews available at the moment.</p>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
