/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.21
 * Generated at: 2026-05-13 07:11:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class error_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    java.lang.Throwable exception = org.apache.jasper.runtime.JspRuntimeLibrary.getThrowable(request);
    if (exception != null) {
      response.setStatus(jakarta.servlet.http.HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    }
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <title>System Message - E-Store</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("  <style>\r\n");
      out.write("    body {\r\n");
      out.write("      font-family: 'Segoe UI', sans-serif;\r\n");
      out.write("      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      justify-content: center;\r\n");
      out.write("      height: 100vh;\r\n");
      out.write("      margin: 0;\r\n");
      out.write("    }\r\n");
      out.write("    .error-container {\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      padding: 40px;\r\n");
      out.write("      border-radius: 20px;\r\n");
      out.write("      background: rgba(255, 255, 255, 0.95);\r\n");
      out.write("      box-shadow: 0 15px 35px rgba(0,0,0,0.2);\r\n");
      out.write("      max-width: 450px;\r\n");
      out.write("      width: 90%;\r\n");
      out.write("    }\r\n");
      out.write("    .icon-circle {\r\n");
      out.write("      width: 80px;\r\n");
      out.write("      height: 80px;\r\n");
      out.write("      background: #fff5f5;\r\n");
      out.write("      color: #ff4757;\r\n");
      out.write("      border-radius: 50%;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      justify-content: center;\r\n");
      out.write("      font-size: 40px;\r\n");
      out.write("      margin: 0 auto 20px;\r\n");
      out.write("    }\r\n");
      out.write("    h1 { color: #2d3436; margin-bottom: 10px; font-size: 32px; }\r\n");
      out.write("    p { color: #636e72; font-size: 16px; line-height: 1.6; }\r\n");
      out.write("    .error-msg-box {\r\n");
      out.write("      font-family: 'Consolas', monospace;\r\n");
      out.write("      background: #f1f2f6;\r\n");
      out.write("      padding: 15px;\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      color: #ff4757;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("      border-left: 4px solid #ff4757;\r\n");
      out.write("      margin: 20px 0;\r\n");
      out.write("      text-align: left;\r\n");
      out.write("      font-size: 14px;\r\n");
      out.write("    }\r\n");
      out.write("    .btn-home {\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("      margin-top: 20px;\r\n");
      out.write("      padding: 12px 30px;\r\n");
      out.write("      background: #764ba2;\r\n");
      out.write("      color: white;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      font-weight: 600;\r\n");
      out.write("      transition: 0.3s;\r\n");
      out.write("    }\r\n");
      out.write("    .btn-home:hover {\r\n");
      out.write("      background: #667eea;\r\n");
      out.write("      transform: translateY(-2px);\r\n");
      out.write("      box-shadow: 0 5px 15px rgba(0,0,0,0.1);\r\n");
      out.write("    }\r\n");
      out.write("    .footer-note { font-size: 12px; color: #a4b0be; margin-top: 20px; }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"error-container\">\r\n");
      out.write("  <div class=\"icon-circle\">\r\n");
      out.write("    <i class=\"fas fa-exclamation-triangle\"></i>\r\n");
      out.write("  </div>\r\n");
      out.write("  <h1>System Alert</h1>\r\n");
      out.write("  <p>We couldn't complete your request at the moment due to the following reason:</p>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"error-msg-box\">\r\n");
      out.write("    <i class=\"fas fa-bug\"></i>\r\n");
      out.write("    ");
      out.print( (request.getAttribute("errorMessage") != null) ? request.getAttribute("errorMessage") : "An unexpected internal error occurred." );
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <p style=\"font-size: 14px;\">If this was a Rate Limit, please wait 5 seconds. For database issues, contact the system admin.</p>\r\n");
      out.write("\r\n");
      out.write("  <a href=\"ProductsMain\" class=\"btn-home\"><i class=\"fas fa-arrow-left\"></i> Back to Dashboard</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
