/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.21
 * Generated at: 2026-05-09 19:15:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.ecommerce.ecommerce.model.Product;
import com.ecommerce.ecommerce.model.Review;
import java.util.List;

public final class product_002ddetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.ecommerce.ecommerce.model.Product");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.ecommerce.ecommerce.model.Review");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  ");
 Product p = (Product) request.getAttribute("product"); 
      out.write("\r\n");
      out.write("  <title>Details - ");
      out.print( p.getName() );
      out.write("</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("  <style>\r\n");
      out.write("    body { font-family: 'Segoe UI', sans-serif; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); min-height: 100vh; margin: 0; display: flex; align-items: center; justify-content: center; padding: 20px; }\r\n");
      out.write("    .main-wrapper { background: white; padding: 40px; border-radius: 25px; box-shadow: 0 20px 50px rgba(0,0,0,0.3); max-width: 550px; width: 100%; text-align: center; }\r\n");
      out.write("    .product-img { width: 100%; max-width: 300px; border-radius: 20px; box-shadow: 0 10px 30px rgba(0,0,0,0.15); margin-bottom: 25px; }\r\n");
      out.write("    h1 { color: #2d3436; margin: 10px 0; font-size: 32px; }\r\n");
      out.write("    .price { color: #2ed573; font-size: 38px; font-weight: bold; margin: 15px 0; }\r\n");
      out.write("    .description { color: #636e72; line-height: 1.8; margin-bottom: 30px; font-size: 16px; text-align: justify; padding: 0 10px; }\r\n");
      out.write("\r\n");
      out.write("    .reviews-section { text-align: left; margin-top: 30px; padding-top: 25px; border-top: 2px solid #f1f2f6; }\r\n");
      out.write("    .reviews-section h3 { color: #764ba2; margin-bottom: 15px; }\r\n");
      out.write("    .reviews-container { max-height: 250px; overflow-y: auto; padding-right: 8px; }\r\n");
      out.write("    .reviews-container::-webkit-scrollbar { width: 5px; }\r\n");
      out.write("    .reviews-container::-webkit-scrollbar-thumb { background: #764ba2; border-radius: 10px; }\r\n");
      out.write("\r\n");
      out.write("    .review-card { background: #f9f9ff; padding: 15px; margin-bottom: 12px; border-radius: 15px; border-left: 5px solid #667eea; }\r\n");
      out.write("    .stars { color: #ffa502; margin-bottom: 5px; }\r\n");
      out.write("    .back-btn { background: #764ba2; color: white; text-decoration: none; padding: 14px 40px; border-radius: 15px; font-weight: 600; display: inline-block; margin-top: 25px; transition: 0.3s; }\r\n");
      out.write("    .back-btn:hover { background: #667eea; transform: scale(1.05); }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"main-wrapper\">\r\n");
      out.write("  <img src=\"");
      out.print( (p.getImageUrl() != null && !p.getImageUrl().isEmpty()) ? p.getImageUrl() : "https://via.placeholder.com/300x200?text=No+Image" );
      out.write("\" class=\"product-img\">\r\n");
      out.write("  <h1>");
      out.print( p.getName() );
      out.write("</h1>\r\n");
      out.write("  <div class=\"price\">$");
      out.print( String.format("%.2f", p.getPrice()) );
      out.write("</div>\r\n");
      out.write("  <p class=\"description\">");
      out.print( p.getDescription() );
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"reviews-section\">\r\n");
      out.write("    <h3><i class=\"fas fa-star\"></i> Item Feedback</h3>\r\n");
      out.write("    <div class=\"reviews-container\">\r\n");
      out.write("      ");

        List<Review> reviews = (List<Review>) request.getAttribute("productReviews");
        if(reviews != null && !reviews.isEmpty()) {
          for(Review r : reviews) {
      
      out.write("\r\n");
      out.write("      <div class=\"review-card\">\r\n");
      out.write("        <div style=\"display: flex; justify-content: space-between; align-items: center;\">\r\n");
      out.write("          <small><b><i class=\"fas fa-user-circle\"></i> ");
      out.print( r.getUsername() );
      out.write("</b></small>\r\n");
      out.write("          <div class=\"stars\">");
 for(int i=0; i<r.getRating(); i++) { 
      out.write('★');
 } 
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <p style=\"font-size: 0.9em; margin: 8px 0 0; color: #444;\">");
      out.print( r.getComment() );
      out.write("</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      ");
 } } else { 
      out.write("\r\n");
      out.write("      <p style=\"text-align: center; color: #bbb;\">No one has reviewed this yet.</p>\r\n");
      out.write("      ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <a href=\"ProductsMain\" class=\"back-btn\"><i class=\"fas fa-arrow-left\"></i> Return to Inventory</a>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
